spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/flexlease}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:flexlease}
    password: ${SPRING_DATASOURCE_PASSWORD:flexlease}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: users
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    create-schemas: true
    default-schema: users
    schemas: users
    locations: classpath:db/migration
server:
  port: ${SERVER_PORT:9002}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:flexlease-default-secret-please-change}
    issuer: ${SECURITY_JWT_ISSUER:flexlease-auth-service}
    internal-access-token: ${SECURITY_JWT_INTERNAL:flexlease-internal-secret}

flexlease:
  auth-service:
    base-url: http://auth-service
    internal-token: ${FLEXLEASE_AUTH_SERVICE_INTERNAL_TOKEN:flexlease-internal-secret}
  notification-service:
    base-url: ${FLEXLEASE_NOTIFICATION_SERVICE_BASE_URL:http://notification-service/api/v1}
