spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/flexlease}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:flexlease}
    password: ${SPRING_DATASOURCE_PASSWORD:flexlease}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "notification"
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false
  flyway:
    enabled: true
    create-schemas: true
    default-schema: "notification"
    schemas: "notification"
    locations: classpath:db/migration
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
server:
  port: ${SERVER_PORT:9006}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
flexlease:
  messaging:
    enabled: ${FLEXLEASE_MESSAGING_ENABLED:true}
  redis:
    enabled: ${FLEXLEASE_REDIS_ENABLED:true}
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:flexlease-default-secret-please-change}
    issuer: ${SECURITY_JWT_ISSUER:flexlease-auth-service}
    internal-access-token: ${SECURITY_JWT_INTERNAL:flexlease-internal-secret}
