spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/flexlease}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:flexlease}
    password: ${SPRING_DATASOURCE_PASSWORD:flexlease}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    create-schemas: true
    default-schema: auth
    schemas: auth
    locations: classpath:db/migration
server:
  port: ${SERVER_PORT:9001}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:flexlease-default-secret-please-change}
    access-token-ttl-seconds: ${SECURITY_JWT_ACCESS_TOKEN_TTL_SECONDS:3600}
    issuer: ${SECURITY_JWT_ISSUER:flexlease-auth-service}
    internal-access-token: ${SECURITY_JWT_INTERNAL:flexlease-internal-secret}

logging:
  level:
    org.springframework.security: INFO
