spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/flexlease}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:flexlease}
    password: ${SPRING_DATASOURCE_PASSWORD:flexlease}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "payment"
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false
  flyway:
    enabled: true
    create-schemas: true
    default-schema: "payment"
    schemas: "payment"
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: ${SERVER_PORT:9005}
flexlease:
  notification-service:
    base-url: http://notification-service/api/v1
  order-service:
    base-url: http://order-service/api/v1
management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:flexlease-default-secret-please-change}
    issuer: ${SECURITY_JWT_ISSUER:flexlease-auth-service}
    internal-access-token: ${SECURITY_JWT_INTERNAL:flexlease-internal-secret}
