spring:
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/flexlease}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:flexlease}
    password: ${SPRING_DATASOURCE_PASSWORD:flexlease}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: product
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    create-schemas: true
    default-schema: product
    schemas: product
    locations: classpath:db/migration
server:
  port: ${SERVER_PORT:9003}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://registry-service:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
flexlease:
  storage:
    root: ${FLEXLEASE_STORAGE_ROOT:/app/storage/uploads}
  inventory:
    concurrency:
      max-attempts: ${FLEXLEASE_INVENTORY_MAX_ATTEMPTS:40}
      backoff: ${FLEXLEASE_INVENTORY_BACKOFF:2ms}
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:flexlease-default-secret-please-change}
    issuer: ${SECURITY_JWT_ISSUER:flexlease-auth-service}
    internal-access-token: ${SECURITY_JWT_INTERNAL:flexlease-internal-secret}
